cat \
js/etc/Vector.js \
js/etc/AI.js \
js/etc/Sound.js \
js/etc/Timer.js \
js/etc/Input.js \
js/scene/Scene.js \
js/scene/ScriptScene.js \
js/scene/SceneManager.js \
js/scene/CreditsScene.js \
js/scene/GameScene.js \
js/scene/mspacman/* \
js/scene/pacman/* \
js/maze/Tile.js \
js/maze/Maze.js \
js/maze/mazes/* \
js/draw/Sprite.js \
js/draw/Text.js \
js/draw/PacmanPoints.js \
js/draw/MsPacmanPoints.js \
js/hud/* \
js/actors/Actor.js \
js/actors/Pacman.js \
js/actors/MsPacman.js \
js/actors/ghosts/Ghost.js \
js/actors/ghosts/Blinky.js \
js/actors/ghosts/Pinky.js \
js/actors/ghosts/Inky.js \
js/actors/ghosts/Clyde.js \
js/actors/ghosts/ScatterChase.js \
js/items/Pellet.js \
js/items/Energizer.js \
js/items/MsPacmanFruit.js \
js/items/PacmanFruit.js \
js/Game.js \
js/index.js \
> jspacman.js
